import { type GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";

import Layout from "~/components/Layout";
import { getServerSession } from "next-auth";
import { authOptions } from "~/server/auth";

export async function getServerSideProps(context: GetServerSidePropsContext) {
    console.log("This is running?")
    const session = await getServerSession(
        context.req, context.res, authOptions
    );

    if (!session) {
        return {
            redirect: {
                destination: "/login",
                permanent: false
            }
        }
    }

    return {
        props: {
            session: session
        }
    }

}

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Todo Time Tracker</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Layout />
            </main>
        </>
    );
};

export default Home;
